global:
  scrape_interval: 15s

scrape_configs:
  # Local Docker app monitoring
  - job_name: 'shieldops-local'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']

  # Deployed Render app monitoring
  - job_name: 'shieldops-render'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['shieldops-eiqm.onrender.com']