# ZAP Baseline Scan Configuration
# Format: <ruleId> <IGNORE|INFO|WARN|FAIL> [comment]

10109	IGNORE	(Modern Web Application)
10055	IGNORE	(CSP: script-src unsafe-inline)
10063	IGNORE	(Permissions Policy Header Not Set)
90004	IGNORE	(Insufficient Site Isolation)
10049	IGNORE	(Non-Storable Content)
