# ZAP Baseline Scan Configuration
# Format: <ruleId> <IGNORE|INFO|WARN|FAIL> [comment]

10109	IGNORE	(Private IP Disclosure)
10055	IGNORE	(CSP: script-src unsafe-inline)
10063	IGNORE	(Permissions Policy Header Not Set)
90004	IGNORE	(Insufficient Site Isolation Support)
10049	IGNORE	(Content Cacheability)
